version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies for development..."
      - npm install -g serverless
  pre_build:
    commands:
      - echo "Installing project dependencies for development..."
      - npm install
  build:
    commands:
      - echo "Deploying to development environment..."
      - serverless deploy --stage dev
artifacts:
  files:
    - "**/*"
  discard-paths: yes
