version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo "Installing dependencies for production..."
      - npm install -g serverless
  pre_build:
    commands:
      - echo "Installing project dependencies for production..."
      - npm install
  build:
    commands:
      - echo "Deploying to production environment..."
      - serverless deploy --stage prod
artifacts:
  files:
    - "**/*"
  discard-paths: yes
